import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import getCurrentUser from "./actions/getCurrentUser";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
